kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: devops-rolebinding
  namespace: easypay
subjects:
  - kind: User
    name: devops
    apiGroup: ""
roleRef:
  kind: Role
  name: devops-role
  apiGroup: ""

